[package]
name = "tcp-echo-server"
version = "0.0.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[[bin]]
name = "tcp-echo-server"
path = "src/main.rs"

[dependencies]
anyhow = "1"
helper-common = { path = "../helper-common" }
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "macros", "signal", "time", "sync"] }
tracing = "0.1"
