worker_processes auto;
events { worker_connections 4096; }
http {
  access_log off;
  server {
    listen 80;
    keepalive_requests 100000;
    location / {
      return 200 "ok\n";
      add_header Content-Type text/plain;
    }
  }
}
