[package]
name = "envoy-bin"
version = "0.0.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[[bin]]
name = "envoy-bin"
path = "src/main.rs"

[dependencies]
anyhow = "1"
envoy-config = { path = "../envoy-config" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "signal", "time", "sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
