[package]
name = "envoy-bin"
version = "0.0.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[[bin]]
name = "envoy-bin"
path = "src/main.rs"

[dependencies]
anyhow = "1"
envoy-admin = { path = "../envoy-admin" }
envoy-cluster = { path = "../envoy-cluster" }
envoy-config = { path = "../envoy-config" }
envoy-http1 = { path = "../envoy-http1" }
envoy-http2 = { path = "../envoy-http2" }
envoy-listener = { path = "../envoy-listener" }
envoy-stats = { path = "../envoy-stats" }
envoy-tcp = { path = "../envoy-tcp" }
envoy-tls = { path = "../envoy-tls" }
httparse = "1"
serde_yaml = "0.9"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "signal", "time", "sync", "process"] }
tokio-util = { version = "0.7", features = ["default"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[dev-dependencies]
bytes = "1"
h2 = "0.4"
http = "1"
rcgen = "0.13"
rustls = { version = "0.23", default-features = false, features = ["std", "tls12"] }
rustls-pki-types = "1"
serde_json = "1"
tempfile = "3"
tokio-rustls = { version = "0.26", default-features = false, features = ["aws-lc-rs"] }
