[package]
name = "envoy-listener"
version = "0.0.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
name = "envoy_listener"
path = "src/lib.rs"

[dependencies]
envoy-config = { path = "../envoy-config" }
envoy-stats = { path = "../envoy-stats" }
socket2 = { version = "0.6", features = ["all"] }
thiserror = "2"
tokio = { version = "1", features = ["rt", "net", "macros", "time", "sync"] }
tracing = "0.1"

[dev-dependencies]
serde_yaml = "0.9"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "net", "macros", "time", "sync", "io-util"] }
