[package]
name = "envoy-health"
version = "0.0.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
name = "envoy_health"
path = "src/lib.rs"

[dependencies]
envoy-cluster = { path = "../envoy-cluster" }
envoy-config = { path = "../envoy-config" }
envoy-http1 = { path = "../envoy-http1" }
envoy-stats = { path = "../envoy-stats" }
thiserror = "2"
tokio = { version = "1", features = ["rt", "macros", "time", "sync", "net", "io-util"] }
tokio-util = { version = "0.7", features = ["rt"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "test-util"] }
